# Generated by Django 2.1.2 on 2018-10-28 21:07

from django.db import migrations, models
import django.db.models.deletion
import produto.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_desc', models.CharField(choices=[('Processadores', 'PROCESADORES'), ('Memória RAM', 'MEMORIARAM'), ('Disco Rígido/SSD', 'DISCORIGIDO'), ('Placa de Vídeo', 'PLACAVIDEO'), ('Gabinete', 'GABINETE'), ('Placa mãe', 'PLACAMAE'), ('Fonte', 'FONTE')], max_length=32, validators=[produto.models.categoria_range])),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacoes', models.TextField(blank=True, max_length=250, null=True)),
                ('preco', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Categoria')),
            ],
        ),
    ]
