# Generated by Django 2.1.2 on 2018-10-29 01:14

from django.db import migrations

def create_categorias(apps, schema_editor):
    Categoria = apps.get_model('produto', 'Categoria')
    Categoria.objects.create(categoria_desc='Processadores')
    Categoria.objects.create(categoria_desc='Memória RAM')
    Categoria.objects.create(categoria_desc='Disco Rígido/SSD')
    Categoria.objects.create(categoria_desc='Placa de Vídeo')
    Categoria.objects.create(categoria_desc='Gabinete')
    Categoria.objects.create(categoria_desc='Placa mãe')
    Categoria.objects.create(categoria_desc='Fonte')

class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categorias),
    ]
